Dev 18195
productsupcom/bin-cde-amazon-s3-parquet pull request #12
Opened 2024-08-02 12:27 UTC by khelmrich

Main codebase without test. Next PR will be with tests

2024-08-05 06:11 UTC, jacekgadomski requested changes
nice, some minor things to fix

2024-08-05 12:27 UTC, khelmrich commented on src/Import/Domain/DuckDb/FileConverter.php
> +{
moved to application layer and renamed

2024-08-05 14:00 UTC, khelmrich commented on src/Import/Infrastructure/Transporter/Exception/ConnectionException.php
> +final class ConnectionException extends ClientLevelException
it was not used I deleted this class

2024-08-05 14:04 UTC, khelmrich commented on src/Import/Infrastructure/Transporter/Exception/ConnectionException.php
> +            message: $previous->getMessage(),
class not needed, has been deleted

2024-08-06 11:40 UTC, khelmrich commented on Dockerfile
> +RUN wget https://github.com/duckdb/duckdb/releases/download/v1.0.0/duckdb_cli-linux-amd64.zip \
https://productsup.atlassian.net/browse/DEV-18652

I have created ticket for this

2024-08-06 11:41 UTC, khelmrich commented on config/services.yaml
> +            $tempFilename: '%temp_filename%'
I am using it in two places. I want to make sure that it is the same for both classes. One is downloading second converting it.

2024-08-06 11:44 UTC, khelmrich commented on src/Import/Infrastructure/Transporter/Exception/DownloadFailed.php
> +final class DownloadFailed extends EngineeringLevelException
not exist I will add it to the framework

2024-08-06 12:52 UTC, jacekgadomski approved these changes

2024-08-06 12:52 UTC, jacekgadomski commented on .env
> +AWS_SECRET_ACCESS_KEY=
rememeber to add this as a secret in the connector config

2024-08-06 12:52 UTC, jacekgadomski commented on config/services.yaml
> +            $tempFilename: '%temp_filename%'
ah ok i thought that it is configurable

2024-08-06 12:52 UTC, jacekgadomski commented on src/Import/Infrastructure/Transporter/Exception/DownloadFailed.php
> +final class DownloadFailed extends EngineeringLevelException
when? it would be good to add it now and do not have it here

2024-08-06 12:52 UTC, khelmrich commented on .env
> +AWS_SECRET_ACCESS_KEY=
I will :)

2024-08-06 14:36 UTC, merged